'use client';
import {use,useEffect,useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import toast from 'react-hot-toast';
import {Check,ShoppingCart} from 'lucide-react';
import {ProductApi} from '@/services/api/product/productApi';
import type {ProductBundleDto} from '@/models/ProductBundle/ProductBundle';
import {useAppDispatch} from '@/store/hooks';
import {addToCart} from '@/store/feature/cart/cartThunks';
import styles from './BundleDetail.module.scss';
import { formatPrice } from '@/utils/price';
export default function BundleDetail({params}:{params:Promise<{id:string}>}){const{id}=use(params);const dispatch=useAppDispatch();const[bundle,setBundle]=useState<ProductBundleDto|null>(null);const[loading,setLoading]=useState(true);const[adding,setAdding]=useState(false);useEffect(()=>{ProductApi.getBundleById(id).then(r=>setBundle(r.data.data??null)).finally(()=>setLoading(false))},[id]);const addAll=async()=>{if(!bundle?.items?.length)return;setAdding(true);try{for(const x of bundle.items)await dispatch(addToCart({productId:x.productId,quantity:x.quantity||1})).unwrap();toast.success('تمام اقلام بسته به سبد خرید اضافه شدند.')}catch{toast.error('موجودی اقلام بسته را بررسی کنید.')}finally{setAdding(false)}};if(loading)return <main className={styles.state}>در حال دریافت بسته…</main>;if(!bundle)return <main className={styles.state}>بسته پیدا نشد.</main>;const price=bundle.price??bundle.items?.reduce((a,x)=>a+(x.unitPrice??0)*x.quantity,0)??0;return <main className={styles.page} dir="rtl"><Link href="/bundles" className={styles.back}>بازگشت به بسته‌ها</Link><div className={styles.layout}><section className={styles.gallery}><div className={styles.mainImage}><Image src="/figma-assets/bundle-service-main.png" fill alt={bundle.name} priority/></div><div className={styles.thumbs}><button><Image src="/figma-assets/bundle-service-thumb-engine.png" fill alt="قطعات بسته"/></button><button><Image src="/figma-assets/bundle-service-thumb-parts.png" fill alt="اقلام بسته"/></button></div></section><section className={styles.info}><span>بسته پیشنهادی کارنیکس</span><h1>{bundle.name}</h1><p>{bundle.description||'مجموعه‌ای از قطعات منتخب و سازگار برای سرویس بهتر خودرو'}</p><div className={styles.price}>{formatPrice(price)} <small>تومان</small></div><ul>{bundle.items?.map(x=><li key={x.productBundleItemId}><Check/><Link href={`/product/${x.productId}`}>{x.productName||`محصول ${x.productId}`}</Link><b>{x.quantity.toLocaleString('fa-IR')} عدد</b></li>)}</ul><button className={styles.add} onClick={addAll} disabled={adding||!bundle.items?.length}><ShoppingCart/>{adding?'در حال افزودن…':'افزودن کل بسته به سبد خرید'}</button></section></div><aside className={styles.compat}><h2>بررسی سازگاری با خودرو</h2><p>خودروی خود را در گاراژ انتخاب کنید تا سازگاری قطعات این بسته با آن بررسی شود.</p><Link href="/profile/garage">رفتن به گاراژ من</Link></aside></main>}
