'use client'
import React,{useState}from'react'
import{IconPhone,IconUser,IconPackage,IconCategory,IconMapPin,IconBuilding,IconMessage,IconSend,IconCheck}from'@tabler/icons-react'
import toast from'react-hot-toast'
import{wholesaleApi,type WholesaleRequestInput}from'@/features/wholesale/api/wholesaleApi'
import styles from'./WholesalePage.module.scss'
type Errors=Partial<Record<keyof WholesaleRequestInput,string>>
const empty:WholesaleRequestInput={phone:'',firstName:'',lastName:'',products:'',category:'',city:'',province:'',description:''}
const categories=['قطعات موتوری','قطعات بدنه','قطعات برقی','لوازم جانبی','روغن و فیلتر','لاستیک و رینگ','سایر']
const provinces=['آذربایجان شرقی','آذربایجان غربی','اردبیل','اصفهان','البرز','ایلام','بوشهر','تهران','چهارمحال و بختیاری','خراسان جنوبی','خراسان رضوی','خراسان شمالی','خوزستان','زنجان','سمنان','سیستان و بلوچستان','فارس','قزوین','قم','کردستان','کرمان','کرمانشاه','کهگیلویه و بویراحمد','گلستان','گیلان','لرستان','مازندران','مرکزی','هرمزگان','همدان','یزد']
export default function WholesalePage(){
 const[data,setData]=useState(empty),[errors,setErrors]=useState<Errors>({}),[busy,setBusy]=useState(false),[code,setCode]=useState('')
 const change=(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>{const name=e.target.name as keyof WholesaleRequestInput;setData(x=>({...x,[name]:e.target.value}));setErrors(x=>({...x,[name]:undefined}))}
 const validate=()=>{const next:Errors={};if(!/^09\d{9}$/.test(data.phone.replace(/\s/g,'')))next.phone='شماره موبایل معتبر وارد کنید.';for(const key of['firstName','lastName','products','category','city','province']as const)if(!data[key].trim())next[key]='تکمیل این فیلد الزامی است.';setErrors(next);return!Object.keys(next).length}
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!validate())return;setBusy(true);try{const result=await wholesaleApi.create(data);setCode(result.trackingCode);setData(empty)}catch{toast.error('ثبت درخواست انجام نشد؛ دوباره تلاش کنید.')}finally{setBusy(false)}}
 if(code)return <div className={styles.page}><div className={styles.container}><div className={styles.successState}><div className={styles.successIcon}><IconCheck size={48}/></div><h2 className={styles.successTitle}>درخواست شما ثبت شد</h2><p className={styles.successText}>کد پیگیری: <strong dir="ltr">{code}</strong></p><p className={styles.successText}>کارشناسان فروش برای هماهنگی با شما تماس می‌گیرند.</p><button className={styles.newRequestButton} onClick={()=>setCode('')}>ثبت درخواست جدید</button></div></div></div>
 const input=(name:keyof WholesaleRequestInput,label:string,Icon:typeof IconUser,placeholder:string)=><div className={`${styles.fieldGroup} ${errors[name]?styles.fieldError:''}`}><label className={styles.label}><Icon size={18}/>{label}<span className={styles.required}>*</span></label><input name={name} value={data[name]} onChange={change} placeholder={placeholder} className={styles.input}/>{errors[name]&&<span className={styles.errorText}>{errors[name]}</span>}</div>
 return <div className={styles.page}><div className={styles.container}><div className={styles.header}><div className={styles.headerIcon}><IconPackage size={32}/></div><h1 className={styles.title}>خرید عمده محصولات</h1><p className={styles.subtitle}>درخواست خود را ثبت کنید تا کارشناسان فروش برای هماهنگی با شما تماس بگیرند.</p></div><form className={styles.form} onSubmit={submit} noValidate><div className={styles.formGrid}>
 {input('phone','شماره تماس',IconPhone,'09123456789')}{input('firstName','نام',IconUser,'نام')}{input('lastName','نام خانوادگی',IconUser,'نام خانوادگی')}{input('products','محصولات',IconPackage,'نام و تعداد محصولات')}
 <div className={`${styles.fieldGroup} ${errors.category?styles.fieldError:''}`}><label className={styles.label}><IconCategory size={18}/>دسته‌بندی<span className={styles.required}>*</span></label><select name="category" value={data.category} onChange={change} className={`${styles.select} unifiedSelect`}><option value="">انتخاب دسته‌بندی</option>{categories.map(x=><option key={x}>{x}</option>)}</select>{errors.category&&<span className={styles.errorText}>{errors.category}</span>}</div>
 {input('city','شهر',IconBuilding,'نام شهر')}
 <div className={`${styles.fieldGroup} ${errors.province?styles.fieldError:''}`}><label className={styles.label}><IconMapPin size={18}/>استان<span className={styles.required}>*</span></label><select name="province" value={data.province} onChange={change} className={`${styles.select} unifiedSelect`}><option value="">انتخاب استان</option>{provinces.map(x=><option key={x}>{x}</option>)}</select>{errors.province&&<span className={styles.errorText}>{errors.province}</span>}</div>
 </div><div className={styles.fieldGroup}><label className={styles.label}><IconMessage size={18}/>توضیحات تکمیلی</label><textarea name="description" value={data.description} onChange={change} className={styles.textarea} rows={4} placeholder="جزئیات مورد نیاز را بنویسید..."/></div><button type="submit" className={styles.submitButton} disabled={busy}>{busy?<><div className={styles.spinner}/>در حال ثبت...</>:<><IconSend size={20}/>ثبت درخواست</>}</button></form></div></div>
}
