import fs from 'node:fs/promises';
import { SpreadsheetFile, Workbook } from '@oai/artifact-tool';

const outputDir = 'D:/Project/Front/Next/New folder/outputs/full-project-audit';
const outputPath = `${outputDir}/CARNIX_PROJECT_FULL_AUDIT.xlsx`;
const wb = Workbook.create();

const issues = [
  ['T-001','کیفیت کد','فرانت','Lint','بالا','قطعی','eslint با ۰ error و ۱۳۷ warning تمام می‌شود.','هشدارهای باقی‌مانده خطای رفتاری یا نگهداری را پنهان می‌کنند.','ui/lint-audit.json؛ npm run lint (2026-09-13)','هشدارها را بر اساس گروه رفع کنید و lint را در CI به معیار اجباری تبدیل کنید.','باز',0,'اندازه‌گیری مستقیم از اجرای lint'],
  ['T-002','Type safety','فرانت','Lint','بالا','قطعی','۸۳ مورد no-explicit-any در UI گزارش شده است.','قرارداد API و state در زمان کامپایل کنترل نمی‌شود.','ui/lint-audit.json؛ rule @typescript-eslint/no-explicit-any','مدل‌های پاسخ و خطا را typed کنید و any را به unknown یا DTO تبدیل کنید.','باز',0,'ابتدا مرزهای API و checkout را اولویت دهید.'],
  ['T-003','کیفیت کد','فرانت','Lint','متوسط','قطعی','۲۱ مورد متغیر بلااستفاده گزارش شده است.','کد مرده و مسیرهای مبهم احتمال خطای تغییرات بعدی را بالا می‌برد.','ui/lint-audit.json؛ rule @typescript-eslint/no-unused-vars','متغیرها و importهای بلااستفاده را حذف یا منطق ناقص را تکمیل کنید.','باز',0,'قابل رفع با lint autofix محدود و review دستی'],
  ['T-004','کارایی React','فرانت','React Hooks','بالا','قطعی','۱۵ مورد set-state-in-effect گزارش شده است.','رندرهای زنجیره‌ای و flicker در جست‌وجو، فیلتر، پروفایل و lazy mount محتمل است.','ui/lint-audit.json؛ rule react-hooks/set-state-in-effect','مقدار مشتق‌شده را در render/useMemo بسازید و effect را فقط برای side effect نگه دارید.','باز',0,'نمونه‌ها در search، vehicles، profile و ProductDetail دیده شد.'],
  ['T-005','پایداری React','فرانت','React Hooks','بالا','قطعی','۷ مورد exhaustive-deps گزارش شده است.','effect ممکن است با state قدیمی اجرا شود یا dependency لازم را از دست بدهد.','ui/lint-audit.json؛ rule react-hooks/exhaustive-deps','dependencyها را اصلاح و effectهای چندمسئولیتی را تفکیک کنید.','باز',0,''],
  ['T-006','پایداری React','فرانت','React Hooks','متوسط','قطعی','۴ مورد دسترسی ناامن به ref گزارش شده است.','خواندن ref در render می‌تواند با React Compiler یا concurrent rendering ناسازگار شود.','ui/lint-audit.json؛ rule react-hooks/refs','ref را فقط داخل event/effect بخوانید و Provider را با الگوی پایدار بسازید.','باز',0,''],
  ['T-007','تست','فرانت و بک','Test coverage','بالا','قطعی','پروژه تست unit/integration/e2e شناخته‌شده یا script تست ندارد؛ فقط verify scriptهای static وجود دارد.','رفتار واقعی checkout، auth، سبد و responsive در برابر regression پوشش ندارد.','ui/package.json؛ ui/scripts/verify-*.mjs؛ نبود فایل test/spec','Playwright یا Cypress برای مسیرهای بحرانی و تست API اضافه کنید.','باز',0,'این ممیزی جای تست پذیرش محصول را نمی‌گیرد.'],
  ['T-008','Build بک‌اند','بک‌اند','Build','بالا','قطعی','dotnet build با Build FAILED تمام شد چون Carnix.exe توسط پروسه Carnix (PID 31560) قفل بود.','نتیجه build قابل تکرار نیست و CI یا release ممکن است متوقف شود.','backend-audit-build.log؛ خطاهای MSB3021/MSB3027','خروجی build را از مسیر اجرا جدا کنید و قبل از build پروسه/خروجی قبلی را مدیریت کنید.','باز',0,'خطا با source compile اشتباه نشود؛ lock محیطی در اجرای جاری ثبت شد.'],
  ['T-009','امنیت وابستگی','بک‌اند','NuGet audit','بحرانی','قطعی','System.Drawing.Common 4.7.0 و System.Text.Encodings.Web 4.5.0 با NU1904 گزارش شدند.','آسیب‌پذیری بحرانی در زنجیره تولید می‌تواند به compromise یا denial of service منجر شود.','backend-audit-build.log؛ NU1904','نسخه امن سازگار را ارتقا دهید، dependency graph را بازبینی و audit را در CI fail کنید.','باز',0,'قبل از انتشار production اولویت صفر'],
  ['T-010','امنیت وابستگی','بک‌اند','NuGet audit','بالا','قطعی','AutoMapper 12.0.1، Microsoft.Data.SqlClient 2.1.4 و Memory 6.0.1 با NU1903 گزارش شدند.','کتابخانه‌های دارای CVE سطح حمله را افزایش می‌دهند.','backend-audit-build.log؛ NU1903','به نسخه‌های وصله‌شده ارتقا دهید و lockfile/restore را در CI بررسی کنید.','باز',0,''],
  ['T-011','سازگاری runtime','بک‌اند','Dependencies','بالا','قطعی','پروژه‌ها net6.0 هستند ولی چند PackageReference از ASP.NET Core 2.1 و Ghasedak با NU1701 restore شده‌اند.','ناسازگاری runtime و رفتار متفاوت در production محتمل است.','Carnix/*/*.csproj؛ هشدارهای NU1701','نسخه‌های framework-aligned را جایگزین و restore تمیز را روی net8 یا نسخه پشتیبانی‌شده انجام دهید.','باز',0,'ارتقای framework باید با migration plan انجام شود.'],
  ['T-012','کیفیت بک‌اند','بک‌اند','Nullable','متوسط','قطعی','build لااقل هشدارهای CS8601/CS8602/CS8604 در controllerها و serviceها دارد.','null در runtime می‌تواند پاسخ ۵۰۰ یا داده ناقص تولید کند.','backend-audit-build.log؛ AuthController, ProfileController, AddressesController و چند controller محصول','DTOها و guardهای null را اصلاح و nullable warnings را به صفر برسانید.','باز',0,''],
  ['T-013','پیچیدگی سرویس','بک‌اند','Maintainability','بالا','قطعی','ProductService.cs حدود ۲۳۵۹ خط است.','تغییر محصول دامنه اثر بزرگ و تست دشوار دارد.','Carnix/Application/Services/Product/ProductService.cs','سرویس list/detail/pricing/media/review را به application serviceهای کوچک تقسیم کنید.','باز',0,'خط‌شماری static'],
  ['T-014','پیچیدگی سرویس','بک‌اند','Maintainability','بالا','قطعی','GenericService.cs حدود ۲۲۲۱ خط است.','generic behavior بیش از حد گسترده و خطاهای پنهان در endpointهای مختلف ایجاد می‌کند.','Carnix/Application/Services/Common/GenericService.cs','قراردادهای محدود و سرویس‌های domain-specific بسازید.','باز',0,''],
  ['T-015','پیچیدگی سرویس','بک‌اند','Maintainability','متوسط','قطعی','ShippingService.cs حدود ۱۶۴۹ خط و AuthService.cs حدود ۱۳۴۰ خط هستند.','تغییرات ارسال و احراز هویت احتمال side effect بین مسیرها دارد.','Carnix/Application/Services/Shipping/ShippingService.cs؛ AuthService.cs','policy، provider و orchestration را تفکیک و تست contract اضافه کنید.','باز',0,''],
  ['T-016','پیچیدگی state','فرانت','Architecture','متوسط','قطعی','productSlice.ts حدود ۱۱۵۱ خط است.','هر تغییر list/detail/filter/bundle دامنه اثر بزرگی دارد.','ui/src/store/feature/product/productSlice.ts','state list، detail، filter و bundle را به مالکیت‌های جدا منتقل کنید.','باز',0,''],
  ['T-017','پیچیدگی component','فرانت','Architecture','متوسط','قطعی','VehicleSelect.tsx حدود ۱۰۲۹ خط است.','کنترل state و responsive آن سخت و regression-prone است.','ui/src/features/vehicle/components/VehicleSelect.tsx','hook داده، dropdown، step و mobile view را تفکیک کنید.','باز',0,''],
  ['T-018','پیچیدگی checkout','فرانت','Architecture','بالا','قطعی','CartStep2.tsx حدود ۶۷۸ خط، cartThunks.ts حدود ۶۷۸ خط و CartStep3.tsx حدود ۶۱۶ خط هستند.','back/refresh و خطاهای مرحله‌ای شکننده می‌شوند.','ui/src/components/cart؛ ui/src/store/feature/cart/cartThunks.ts','ماشین حالت checkout و serviceهای quote/order/payment را جدا و تست کنید.','باز',0,''],
  ['T-019','قرارداد API','فرانت','Data parsing','بالا','قطعی','حداقل ۴۷ الگوی مستقیم response.data.data یا response.data مشابه خارج از adapter محصول باقی مانده است.','تغییر envelope بک‌اند می‌تواند فقط بعضی featureها را خراب کند.','ui/src/store/feature؛ scan پاسخ API در 2026-09-13','یک adapter typed مشترک برای تمام featureها اعمال و schema validation اضافه کنید.','باز',0,'نمونه‌ها در vehicle/profile/address/review/content دیده شد.'],
  ['T-020','Type safety','فرانت','Data model','بالا','قطعی','any در profileThunks، cart dropdown، price utility، CartApi و صفحات brands/vehicles استفاده می‌شود.','خطای شکل داده یا undefined در checkout و پروفایل در compile-time دیده نمی‌شود.','مسیرهای فوق در scan any؛ ui/lint-audit.json','مدل‌های Cart/Profile/Brand/Vehicle و error را کامل typed کنید.','باز',0,''],
  ['T-021','یکپارچگی UI','فرانت','Forms','متوسط','قطعی','۹ native select در ProfileInfo، AddressModal، diagnose و چند مسیر باقی مانده، در کنار AppSelect/VehicleSelect.','ظاهر، keyboard behavior و فاصله dropdownها در صفحات یکسان نیست.','ui/src scan `<select>`؛ 9 مورد','یک primitive مشترک select با label، error، keyboard و mobile behavior استفاده کنید.','باز',0,''],
  ['T-022','امنیت HTML','فرانت','XSS surface','بالا','قطعی','۳ استفاده از dangerouslySetInnerHTML وجود دارد؛ SafeHtml بخشی را sanitize می‌کند اما review همه ورودی‌ها لازم است.','محتوای CMS یا مقاله در صورت sanitize ناقص می‌تواند XSS ایجاد کند.','ui/src؛ scan dangerouslySetInnerHTML','ورودی‌ها را با allowlist محدود، sanitize server/client و تست payload بررسی کنید.','باز',0,'استفاده به‌خودی‌خود آسیب‌پذیری قطعی نیست؛ نیازمند trace منبع داده است.'],
  ['T-023','امنیت تنظیمات','بک‌اند','Configuration','بالا','قطعی','Connection string شامل TrustServerCertificate=True است.','اعتبارسنجی گواهی SQL در محیط production تضعیف می‌شود.','Carnix/Carnix/appsettings.json:3','گواهی معتبر و secret خارج از فایل را برای production اجباری کنید.','باز',0,'برای local development قابل قبول، برای production نیازمند override امن'],
  ['T-024','امنیت تنظیمات','بک‌اند','Configuration','متوسط','قطعی','AllowedHosts در appsettings روی * تنظیم شده است.','سطح host header پذیرفته‌شده بیش از نیاز واقعی است.','Carnix/Carnix/appsettings.json','hostهای production را صریح whitelist کنید.','باز',0,''],
  ['T-025','داده حساس','بک‌اند','Secrets','بحرانی','قطعی','SmsSettings.ApiKey در appsettings خالی و connection string در فایل تنظیمات نگهداری می‌شود.','پیکربندی ناقص یا انتقال secret به source control خطر outage یا افشا دارد.','Carnix/Carnix/appsettings.json:2-21','Secret manager/environment variables و validation startup برای production اضافه کنید.','باز',0,'مقدار فعلی خالی است؛ وجود secret واقعی باید در محیط deploy کنترل شود.'],
  ['T-026','معماری API','فرانت','Duplication','متوسط','قطعی','دو لایه API محصول در features/product/api و services/api/product هم‌زمان وجود دارد.','دو قرارداد و منطق fallback می‌تواند رفتار متفاوت و باگ cache بسازد.','ui/src/features/product/api؛ ui/src/services/api/product','یک مرز API رسمی تعیین و لایه قدیمی را حذف یا مستند کنید.','باز',0,''],
  ['T-027','کارایی تصویر','فرانت','Assets','متوسط','قطعی','چند asset محلی JPG/PNG بین حدود ۲۰۰ تا ۳۵۳KB هستند و نام‌های Screenshot دارند.','حجم اولیه موبایل و LCP بالا می‌رود.','ui/src/assets/images؛ بزرگ‌ترین فایل car-part-4.jpg با 353158 bytes','تصاویر را فشرده/AVIF/WebP کنید و preload/priority را فقط برای hero تنظیم کنید.','باز',0,'next/image فعال است اما منبع خام هنوز سنگین است.'],
  ['T-028','پایداری نشست','فرانت و بک','Auth','بالا','قطعی','refresh و cookie امن در کد وجود دارد، اما پذیرش واقعی rotation/revoke و هم‌زمانی چند request با API زنده تست نشده است.','انقضای access token می‌تواند به logout ناخواسته یا refresh race منجر شود.','ui/src/services/api/common/axiosClient.ts؛ ui/src/app/api/auth/refresh/route.ts','سناریوی expiry، rotation، revoke، دو تب و replay را با API واقعی تست کنید.','نیازمند تست',50,'check:critical پاس است اما تست زنده کامل نیست.'],
  ['T-029','پرداخت','فرانت و بک','Checkout','بحرانی','قطعی','state machine و endpointهای payment در کد دیده می‌شوند، اما gateway واقعی و callback/verify در محیط پذیرش اجرا نشده است.','نمایش موفقیت بدون تراکنش تأییدشده ممکن است.','ui/src/features/checkout؛ Carnix/Carnix/Controllers/PaymentController.cs','تست end-to-end با sandbox gateway، idempotency و callback replay اضافه کنید.','نیازمند تست',70,''],
  ['T-030','داده سفارش','فرانت و بک','Orders','بالا','قطعی','صفحه cart بدون session ابتدا پیام loading نشان می‌دهد و در runtime بین SSR و client mismatch رخ می‌دهد.','کاربر flicker می‌بیند و React بخشی از tree را دوباره می‌سازد.','runtime `/cart`؛ console: Hydration failed؛ CartPage','render اولیه را deterministic کنید و auth/session را بعد از mount بدون تغییر متن SSR هماهنگ کنید.','باز',0,'خطا در مرورگر در 2026-09-13 مشاهده شد.'],
  ['T-031','پایداری SSR','فرانت','Hydration','بالا','قطعی','در runtime، navigation از `/cart` و `/mechanics/dashboard` لاگ hydration mismatch را نشان داد.','SSR/CSR divergence می‌تواند state و event handler را از دسترس خارج کند.','runtime console؛ React hydration mismatch stack','تمام branchهای وابسته به window، localStorage و زمان را از render SSR حذف یا snapshot کنید.','باز',0,'/products در همان session بدون console error رندر شد.'],
  ['T-032','داده محصول','فرانت و بک','Runtime data','متوسط','قطعی','`/products` در runtime با پیام «خودرویی برای نمایش وجود ندارد» و کارت‌های بدون تصویر باز شد.','در نبود داده یا خطای API، ارزش صفحه و اعتماد کاربر افت می‌کند.','runtime `/products`؛ DOM text و کارت‌های بدون تصویر','حالت empty/error را از unavailable API تفکیک و داده seed/observability محیط را بررسی کنید.','نیازمند بررسی',50,'ممکن است ناشی از محیط داده محلی باشد.'],
  ['T-033','کنترل دسترسی','بک‌اند','Authorization','بالا','قطعی','بسیاری از controllerها ApiTokenScheme دارند اما ترکیب AllowAnonymous در endpointهای متعدد نیازمند ماتریس دسترسی مستند است.','یک annotation اشتباه می‌تواند داده سفارش/آدرس را عمومی کند.','Carnix/Carnix/Controllers scan Authorize/AllowAnonymous','ماتریس public/authenticated/admin بسازید و contract test برای هر endpoint اجرا کنید.','باز',0,'وجود AllowAnonymous به‌تنهایی خطا نیست؛ coverage دسترسی ثبت نشده است.'],
  ['T-034','ساختار workspace','بک‌اند','Repository hygiene','متوسط','قطعی','هزاران پوشه publish/phase*-bin درخت Carnix را آلوده کرده‌اند (حدود ۱۰۲۶۶ directory تولیدی).','جست‌وجو، backup و deploy کند و احتمال commit artifact زیاد می‌شود.','Carnix recursive directory scan 2026-09-13','artifactهای build را بیرون source نگه دارید و .gitignore/cleanup policy اعمال کنید.','باز',0,'ممکن است ignored باشند اما هزینه عملیاتی دارند.'],
  ['T-035','صفحه تنظیمات','فرانت و بک','Admin','بالا','نیازمند بررسی','SiteSettingsController فقط PUT را با RequireAdminRole محدود کرده، اما seed/default و مقدار واقعی production باید با admin UI تطبیق داده شود.','footer و لینک‌های ارتباطی ممکن است با داده پیش‌فرض نمایش داده شوند.','Carnix/Carnix/Controllers/SiteSettingsController.cs؛ Footer.tsx','تست role و update/read round-trip و داده production را ثبت کنید.','نیازمند تست',50,''],
  ['T-036','ساخت production','فرانت','Build','بالا','نیازمند تست','typecheck و verify scriptها پاس شدند، اما npm run build کامل در این ممیزی اجرا و نتیجه مستقل ثبت نشد.','خطای build/SSG ممکن است بعد از تغییرات runtime آشکار شود.','ui/package.json؛ نبود خروجی build مستقل در evidence','build را در محیط clean با envهای لازم اجرا و artifact را smoke test کنید.','نیازمند تست',50,'این ردیف عمداً ادعای شکست build ندارد.'],
  ['V-001','هدر موبایل','فرانت','Visual/Responsive','متوسط','مشاهده زنده','در عرض ۳۹۰px header با کنترل‌های touch target حدود ۴۴px و logo متنی CARNIX بخش قابل توجهی از ارتفاع نوار را می‌گیرد.','فضای محتوا و تمرکز روی search/hero کم می‌شود.','runtime screenshot خانه در viewport 390x844','مقیاس icon، badge و logo را با design token مشترک و حداقل touch target قابل دسترس متعادل کنید.','نیازمند تست',50,'۴۴px برای دسترسی مفید است؛ تصمیم نهایی باید با design system باشد.'],
  ['V-002','اسکرول کارت‌ها','فرانت','Visual/Responsive','بالا','گزارش کاربر + نیازمند تست','DOM خانه چند overflow container با scrollWidth بیشتر از clientWidth دارد؛ drag direction و حرکت کامل روی موبایل هنوز با دستگاه واقعی اثبات نشده است.','کارت‌ها ممکن است تکه‌ای حرکت کنند، برعکس شوند یا برای بخشی از صفحه قفل شوند.','runtime DOM home در 390px؛ useHorizontalDragScroll.ts','یک primitive carousel واحد با touch-action/pointer capture، RTL test و keyboard control بسازید و روی iOS/Android تست کنید.','نیازمند تست',50,'صفحه در desktop overflow منطقی دارد؛ مشکل اصلی acceptance موبایل است.'],
  ['V-003','کارت محصول موبایل','فرانت','Visual/Responsive','متوسط','گزارش کاربر + مشاهده screenshot','در screenshotهای ارسالی، کارت‌ها و کنترل quantity در عرض کم به لبه تصویر می‌چسبند یا بخشی از کنترل از کادر خارج می‌شود.','قیمت، دکمه سبد و quantity خوانا یا قابل لمس نیستند.','اسکرین‌شات‌های ممیزی کاربر؛ ProductCard.module.scss','عرض کارت را با gap و padding container محاسبه کنید و کنترل را inline-flex با min-width صفر نگه دارید.','نیازمند تست',50,'اصلاحات CSS اخیر نیازمند بازبینی چند عرض 320/360/390 است.'],
  ['V-004','سبد خرید موبایل','فرانت','Visual/Responsive','بالا','مشاهده screenshot','در screenshotهای ارسالی، drawer/cart در موبایل از سمت تصویر به محتوا می‌چسبد و دکمه‌های کم/زیاد/سطل زباله بزرگ یا فشرده‌اند.','کاربر کنترل quantity و حذف را سخت هدف می‌گیرد و متن محصول فشرده می‌شود.','CartDropdown.module.scss؛ screenshotهای cart موبایل','drawer را با max-width:100vw، padding ثابت و control cluster responsive تست کنید.','نیازمند تست',50,'touch target نباید از حد دسترسی پایین‌تر بیاید.'],
  ['V-005','تب محصولات','فرانت','Visual/Responsive','متوسط','گزارش کاربر','در screenshotها عنوان و تب‌های «محصولات ویژه/تخفیف‌دار» در موبایل بزرگ و گاهی هم‌پوشان دیده می‌شوند.','hierarchy و انتخاب تب در صفحه باریک واضح نیست.','FeaturedProductsSection.module.scss؛ screenshotهای home','font/line-height تب‌ها و فاصله header را با container width تطبیق دهید.','نیازمند تست',50,''],
  ['V-006','فوتر موبایل','فرانت','Visual/Responsive','متوسط','گزارش کاربر','تبدیل فوتر به سه ستون در گوشی‌های کوچک می‌تواند لینک‌ها را فشرده و ارتفاع را زیاد کند.','اسکن و کلیک لینک‌های فوتر سخت می‌شود.','Footer.module.scss؛ screenshot footer موبایل','در 320/360/390px با grid سه‌ستونه و breakpoint fallback تست usability انجام دهید.','نیازمند تست',50,''],
  ['V-007','یکپارچگی dropdown','فرانت','Visual/UX','متوسط','گزارش کاربر + static','native selectها کنار AppSelect/VehicleSelect باقی مانده‌اند و spacing/scrollbar یکسان نیست.','کاربر در فرم‌ها رفتار و ظاهر متفاوت می‌بیند.','۹ `<select>` در ui/src؛ AppSelect.module.scss','تمام dropdownها را به primitive واحد منتقل و focus/error/RTL را تست کنید.','باز',0,''],
  ['V-008','مدال‌ها','فرانت','Visual/Accessibility','متوسط','گزارش کاربر','کاربر گزارش کرده مدال‌ها scrollbar نمایان دارند و مدال گاراژ از نظر ابعاد/فاصله یکسان نیست.','بخشی از فرم یا دکمه در viewport کوچک پنهان می‌شود.','AddressModal.module.scss؛ ProductOverViewModal.module.scss؛ GaragePage.module.scss','overflow داخلی را کنترل و max-height، focus trap و responsive width را در همه modalها یکسان کنید.','نیازمند تست',50,''],
  ['V-009','پنل مکانیک','فرانت و بک','Visual/Runtime','بالا','مشاهده زنده','در حالت مهمان `/mechanics/dashboard` بعد از loading به `/login?callbackUrl=...` هدایت می‌شود؛ صفحه پنل بدون session قابل مشاهده نیست.','اگر session معتبر هم همین رفتار را داشته باشد، پنل برای مکانیک‌ها عملاً unavailable است.','runtime `/mechanics/dashboard`؛ P4PlatformController و page route','با role مکانیک و داده واقعی تست کن، loading/error/empty را از redirect تفکیک کن.','نیازمند تست',50,'برای مهمان redirect مورد انتظار است.'],
  ['V-010','تصاویر بدون داده','فرانت','Visual/Content','متوسط','مشاهده زنده','در `/products` کارت‌های «بدون تصویر» دیده شد و داده محصول نمایش داده نشد.','صفحه فروشگاه کم‌اعتماد و از نظر بصری خالی است.','runtime `/products`؛ ProductCard و getMediaUrl','fallback تصویر، seed داده و خطای media API را جداگانه نمایش دهید.','نیازمند بررسی',50,'وابسته به داده/آپلود محیط جاری.'],
  ['V-011','محتوای متنی کارت','فرانت','Visual/Content','کم','مشاهده screenshot','عنوان‌های طولانی فارسی در کارت‌ها به دو یا چند خط می‌شکنند و با قیمت/کنترل نزدیک می‌شوند.','خوانایی و مقایسه سریع محصولات کم می‌شود.','ProductCard.module.scss؛ screenshotهای home','line-clamp، min-height عنوان و فاصله ثابت bottom row تعریف کنید.','نیازمند تست',50,''],
  ['V-012','دسترسی icon button','فرانت','Accessibility','متوسط','نیازمند تست','در DOM تعداد زیادی button آیکونی وجود دارد؛ پوشش aria-label/title در همه مسیرها اثبات نشده است.','screen reader نام کنترل را نمی‌خواند و تست keyboard ضعیف می‌شود.','scan aria-label/title؛ HeaderAction و ProductCard','برای هر icon-only button نام accessible، focus ring و keyboard test اجباری کنید.','باز',0,'وجود aria در بخشی از کد ثبت شده اما coverage کامل نیست.'],
];

const verified = [
  ['C-001','TypeScript','فرانت','npx tsc --noEmit','PASS','کد بدون خطای TypeScript در وضعیت جاری کامپایل شد.','2026-09-13'],
  ['C-002','کنترل‌های بحرانی','فرانت','npm run check:critical','PASS','چک‌های UI-001 تا UI-003 موفق شدند.','2026-09-13'],
  ['C-003','معماری P0','فرانت','npm run check:p0','PASS','کنترل‌های proxy و auth architecture موفق شدند.','2026-09-13'],
  ['C-004','Checkout P1','فرانت','npm run check:p1','PASS','کنترل quote و متن checkout موفق شد.','2026-09-13'],
  ['C-005','P2/P3/P4','فرانت','npm run check:p2 / p3 / p4','PASS','اسکریپت‌های static مرتبط با کیفیت، API و P4 موفق شدند.','2026-09-13'],
  ['C-006','Runtime home','فرانت','localhost:3000 + viewport 390x844','PASS','خانه در موبایل رندر شد، body horizontal overflow نداشت و navigation اصلی حاضر بود.','2026-09-13'],
  ['C-007','Runtime products','فرانت','localhost:3000/products','PASS','صفحه products بدون خطای console در مشاهده جاری باز شد؛ داده محلی خالی بود.','2026-09-13'],
  ['C-008','Runtime auth guard','فرانت و بک','localhost:3000/mechanics/dashboard','PASS','مهمان به login با callbackUrl هدایت شد.','2026-09-13'],
  ['C-009','Security headers','فرانت','ui/next.config.ts','PASS','nosniff، frame deny، referrer policy، permissions policy و HSTS production تعریف شده‌اند.','2026-09-13'],
  ['C-010','Refresh route','فرانت و بک','ui/src/app/api/auth/refresh + Carnix Auth','PASS','مسیر refresh و rotation/revoke در کد موجود و check بحرانی موفق است.','2026-09-13'],
];

const routeRows = [
  ['/','خانه','رندر شد','بدون console error در مشاهده جاری؛ اسکرول افقی داخلی دارد.'],
  ['/products','محصولات','رندر شد','بدون console error؛ داده محلی خالی/بدون تصویر مشاهده شد.'],
  ['/cart','سبد خرید','هشدار','hydration mismatch در console مشاهده شد.'],
  ['/mechanics/dashboard','پنل مکانیک','redirect مهمان','به login هدایت شد؛ role مکانیک تست نشده.'],
  ['/product/[slug]','جزئیات محصول','کد مسیر موجود','تست با slug و داده API در این ممیزی انجام نشد.'],
  ['/payment/callback','callback پرداخت','کد مسیر موجود','تست sandbox gateway انجام نشد.'],
  ['/profile/orders/[id]','جزئیات سفارش','کد مسیر موجود','تست session/order واقعی انجام نشد.'],
  ['/diagnose','تشخیص','کد مسیر موجود','تست API rule/garage انجام نشد.'],
  ['/bulk-purchase','خرید عمده','کد مسیر موجود','submit API در checkهای قبلی دیده شده؛ پذیرش runtime انجام نشد.'],
  ['/blog/[slug]','مقاله','کد مسیر موجود','داده و SSG واقعی این ممیزی اجرا نشد.'],
];

const evidence = [
  ['E-001','Frontend static','ui','npx tsc --noEmit','PASS','2026-09-13'],
  ['E-002','Frontend lint','ui','npx eslint . -f json','0 errors / 137 warnings','2026-09-13'],
  ['E-003','Critical/P0-P4 scripts','ui','npm run check:p0, check:critical, check:p1, check:p2, check:p3, check:p4','همه PASS','2026-09-13'],
  ['E-004','Backend build','Carnix','dotnet build Carnix/Carnix.csproj --no-restore','FAILED: locked Carnix.exe; package and nullable warnings','2026-09-13'],
  ['E-005','Dependency scan','Carnix/*.csproj','build restore warnings','NU1904 critical، NU1903 high، NU1902 moderate، NU1701 compatibility','2026-09-13'],
  ['E-006','Runtime desktop/mobile','localhost:3000','home, products, cart, mechanics/dashboard','home/products rendered; cart hydration error; mechanics guest redirect','2026-09-13'],
  ['E-007','Responsive DOM','localhost:3000','viewport 390x844; scrollWidth/clientWidth','body overflow برابر viewport؛ چند carousel داخلی overflow دارد','2026-09-13'],
  ['E-008','Source inventory','ui/src + Carnix','file/line scan','399 UI source files؛ فایل‌های بزرگ و APIهای موازی ثبت شد','2026-09-13'],
];

const sheetSummary = wb.worksheets.add('خلاصه');
const sheetIssues = wb.worksheets.add('ایرادات فنی و ظاهری');
const sheetVerified = wb.worksheets.add('کنترل‌های تاییدشده');
const sheetRoutes = wb.worksheets.add('پوشش مسیرها');
const sheetEvidence = wb.worksheets.add('شواهد بررسی');

const dark='#173F78', blue='#2563EB', light='#EAF2FF', red='#FEE2E2', amber='#FEF3C7', green='#DCFCE7', gray='#F8FAFC';
const font={name:'Arial',size:10,color:'#172033'};
function styleHeader(range){range.format={fill:dark,font:{name:'Arial',size:10,bold:true,color:'#FFFFFF'},horizontalAlignment:'center',verticalAlignment:'center',wrapText:true};}
function styleBody(range){range.format={font,verticalAlignment:'center',wrapText:true};}
function widths(sheet, specs){for(const [col,w] of Object.entries(specs)) sheet.getRange(`${col}:${col}`).format.columnWidth=w;}

sheetSummary.showGridLines=false; sheetIssues.showGridLines=false; sheetVerified.showGridLines=false; sheetRoutes.showGridLines=false; sheetEvidence.showGridLines=false;
sheetSummary.getRange('A1:H1').merge(); sheetSummary.getRange('A1').values=[['ممیزی کامل پروژه کارنیکس']]; sheetSummary.getRange('A1:H1').format={font:{name:'Arial',size:16,bold:true,color:dark},verticalAlignment:'center'}; sheetSummary.getRange('A2:H2').merge(); sheetSummary.getRange('A2').values=[['دامنه: فرانت Next.js، بک‌اند ASP.NET Core، runtime مرورگر و بررسی ظاهری responsive']]; sheetSummary.getRange('A2:H2').format={font:{name:'Arial',size:10,color:'#475569'},wrapText:true};
sheetSummary.getRange('A4:B10').values=[['تاریخ ممیزی','2026-09-13'],['تعداد کل یافته‌ها',null],['یافته‌های باز',null],['بحرانی',null],['بالا',null],['متوسط',null],['نیازمند تست/بررسی',null]];
sheetSummary.getRange('B5').formulas=[["=COUNTA('ایرادات فنی و ظاهری'!A2:A200)"]]; sheetSummary.getRange('B6').formulas=[["=COUNTIF('ایرادات فنی و ظاهری'!K2:K200,\"باز\")"]]; sheetSummary.getRange('B7').formulas=[["=COUNTIF('ایرادات فنی و ظاهری'!E2:E200,\"بحرانی\")"]]; sheetSummary.getRange('B8').formulas=[["=COUNTIF('ایرادات فنی و ظاهری'!E2:E200,\"بالا\")"]]; sheetSummary.getRange('B9').formulas=[["=COUNTIF('ایرادات فنی و ظاهری'!E2:E200,\"متوسط\")"]]; sheetSummary.getRange('B10').formulas=[["=COUNTIF('ایرادات فنی و ظاهری'!K2:K200,\"نیازمند تست\")+COUNTIF('ایرادات فنی و ظاهری'!K2:K200,\"نیازمند بررسی\")"]];
sheetSummary.getRange('A4:A10').format={font:{name:'Arial',size:10,bold:true,color:dark},fill:light}; sheetSummary.getRange('B4:B10').format={font,fill:'#FFFFFF',horizontalAlignment:'center'};
sheetSummary.getRange('D4:H4').values=[['تفکیک یافته‌ها','تعداد','فرانت','بک‌اند','مشترک']]; styleHeader(sheetSummary.getRange('D4:H4'));
sheetSummary.getRange('D5:D8').values=[['باز'],['نیازمند تست'],['نیازمند بررسی'],['مشاهده زنده / گزارش']]; sheetSummary.getRange('E5').formulas=[["=COUNTIF('ایرادات فنی و ظاهری'!K2:K200,D5)"]]; sheetSummary.getRange('E6').formulas=[["=COUNTIF('ایرادات فنی و ظاهری'!K2:K200,D6)"]]; sheetSummary.getRange('E7').formulas=[["=COUNTIF('ایرادات فنی و ظاهری'!K2:K200,D7)"]]; sheetSummary.getRange('E8').formulas=[["=COUNTIF('ایرادات فنی و ظاهری'!F2:F200,\"مشاهده زنده\")"]];
sheetSummary.getRange('D11:H11').values=[['نتیجه تست','وضعیت','شاهد','محدودیت','اقدام بعدی']]; styleHeader(sheetSummary.getRange('D11:H11')); sheetSummary.getRange('D12:H16').values=[['TypeScript','PASS','npx tsc --noEmit','رفتار runtime را پوشش نمی‌دهد','تست integration'],['Lint','WARN','۰ error / ۱۳۷ warning','warningها باز هستند','رفع warningها'],['P0 تا P4','PASS','تمام verify scriptها','static است','تست browser/e2e'],['Backend build','FAIL','Carnix.exe lock + warnings','lock محیط جاری','build clean/CI'],['Runtime','WARN','cart hydration mismatch','session/data واقعی محدود','رفع mismatch و smoke test']]; styleBody(sheetSummary.getRange('D12:H16'));
sheetSummary.getRange('A13:H13').merge(); sheetSummary.getRange('A13').values=[['روش: یافته‌های قطعی از scan/build/runtime جدا از موارد نیازمند تست ثبت شده‌اند. درصد ساختگی برای موارد تست‌نشده اعمال نشده است.']]; sheetSummary.getRange('A13:H13').format={fill:amber,font:{name:'Arial',size:10,color:'#92400E'},wrapText:true};
widths(sheetSummary,{A:28,B:16,C:4,D:20,E:12,F:22,G:24,H:28}); sheetSummary.getRange('A1:H16').format.verticalAlignment='center'; sheetSummary.getRange('A1:H16').format.rowHeight=24; sheetSummary.getRange('A1:H1').format.rowHeight=30; sheetSummary.freezePanes.freezeRows(3);

const issueHeaders=['شناسه','حوزه','لایه','نوع','شدت','اطمینان','شرح ایراد','اثر/ریسک','شاهد و مسیر','اقدام پیشنهادی','وضعیت','پیشرفت','یادداشت'];
sheetIssues.getRange(`A1:M1`).values=[issueHeaders]; styleHeader(sheetIssues.getRange('A1:M1')); sheetIssues.getRange(`A2:M${issues.length+1}`).values=issues; styleBody(sheetIssues.getRange(`A2:M${issues.length+1}`)); sheetIssues.getRange(`L2:L${issues.length+1}`).format.numberFormat='0%'; sheetIssues.getRange(`L2:L${issues.length+1}`).format.horizontalAlignment='center'; sheetIssues.getRange(`A2:A${issues.length+1}`).format.font={name:'Arial',size:10,bold:true,color:dark}; sheetIssues.getRange(`E2:E${issues.length+1}`).conditionalFormats.add('containsText',{text:'بحرانی',format:{fill:red,font:{color:'#991B1B',bold:true}}}); sheetIssues.getRange(`E2:E${issues.length+1}`).conditionalFormats.add('containsText',{text:'بالا',format:{fill:amber,font:{color:'#92400E',bold:true}}}); sheetIssues.getRange(`K2:K${issues.length+1}`).conditionalFormats.add('containsText',{text:'باز',format:{fill:red,font:{color:'#991B1B'}}}); sheetIssues.getRange(`K2:K${issues.length+1}`).conditionalFormats.add('containsText',{text:'نیازمند تست',format:{fill:amber,font:{color:'#92400E'}}}); widths(sheetIssues,{A:10,B:18,C:14,D:16,E:12,F:12,G:42,H:40,I:42,J:42,K:16,L:12,M:28}); sheetIssues.getRange(`A1:M${issues.length+1}`).format.rowHeight=42; sheetIssues.freezePanes.freezeRows(1); sheetIssues.tables.add(`A1:M${issues.length+1}`,true,'FullAuditIssues');

sheetVerified.getRange('A1:G1').values=[['شناسه','کنترل','لایه','دستور/روش','وضعیت','نتیجه','تاریخ']]; styleHeader(sheetVerified.getRange('A1:G1')); sheetVerified.getRange(`A2:G${verified.length+1}`).values=verified; styleBody(sheetVerified.getRange(`A2:G${verified.length+1}`)); sheetVerified.getRange(`E2:E${verified.length+1}`).format={fill:green,font:{name:'Arial',size:10,bold:true,color:'#166534'},horizontalAlignment:'center'}; widths(sheetVerified,{A:10,B:22,C:16,D:34,E:12,F:52,G:16}); sheetVerified.getRange(`A1:G${verified.length+1}`).format.rowHeight=32; sheetVerified.freezePanes.freezeRows(1); sheetVerified.tables.add(`A1:G${verified.length+1}`,true,'VerifiedControls');

sheetRoutes.getRange('A1:D1').values=[['مسیر','صفحه','وضعیت مشاهده','یادداشت']]; styleHeader(sheetRoutes.getRange('A1:D1')); sheetRoutes.getRange(`A2:D${routeRows.length+1}`).values=routeRows; styleBody(sheetRoutes.getRange(`A2:D${routeRows.length+1}`)); widths(sheetRoutes,{A:28,B:22,C:20,D:70}); sheetRoutes.getRange(`A1:D${routeRows.length+1}`).format.rowHeight=32; sheetRoutes.freezePanes.freezeRows(1); sheetRoutes.tables.add(`A1:D${routeRows.length+1}`,true,'RouteCoverage');

sheetEvidence.getRange('A1:F1').values=[['شناسه','دامنه','هدف','دستور/منبع','نتیجه','تاریخ']]; styleHeader(sheetEvidence.getRange('A1:F1')); sheetEvidence.getRange(`A2:F${evidence.length+1}`).values=evidence; styleBody(sheetEvidence.getRange(`A2:F${evidence.length+1}`)); widths(sheetEvidence,{A:10,B:24,C:24,D:40,E:60,F:16}); sheetEvidence.getRange(`A1:F${evidence.length+1}`).format.rowHeight=34; sheetEvidence.freezePanes.freezeRows(1); sheetEvidence.tables.add(`A1:F${evidence.length+1}`,true,'AuditEvidence');

wb.recalculate();
const summaryCheck=await wb.inspect({kind:'table',range:'خلاصه!A1:H16',include:'values,formulas',tableMaxRows:20,tableMaxCols:10,maxChars:8000}); console.log(summaryCheck.ndjson);
const issueCheck=await wb.inspect({kind:'table',range:`ایرادات فنی و ظاهری!A1:M8`,include:'values,formulas',tableMaxRows:10,tableMaxCols:14,maxChars:8000}); console.log(issueCheck.ndjson);
const errors=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:300},summary:'final formula error scan'}); console.log(errors.ndjson);
await fs.mkdir(outputDir,{recursive:true});
for(const [name,range] of [['خلاصه','A1:H16'],['ایرادات فنی و ظاهری','A1:M12'],['کنترل‌های تاییدشده','A1:G11']]){const p=await wb.render({sheetName:name,range,scale:1,format:'png'}); await fs.writeFile(`${outputDir}/${name}.png`,new Uint8Array(await p.arrayBuffer()));}
const out=await SpreadsheetFile.exportXlsx(wb); await out.save(outputPath); console.log(`SAVED=${outputPath}`); console.log(`ISSUES=${issues.length}`);
