"use client";
import {useCallback,useEffect,useMemo,useState} from 'react'; import type {ResourceConfig,FieldDef} from '@/lib/types'; import {api,fillPath,unwrapData,unwrapList} from '@/lib/api'; import {useToast} from './Toast';
function norm(obj:any,key:string){ if(!obj)return undefined; if(obj[key]!==undefined)return obj[key]; const k=Object.keys(obj).find(x=>x.toLowerCase()===key.toLowerCase()); return k?obj[k]:undefined; }
function format(v:any,render?:string){if(v===null||v===undefined||v==='')return '—'; if(render==='boolean')return v?<span className="badge ok">فعال</span>:<span className="badge muted">غیرفعال</span>; if(render==='money'){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('fa-IR'):'—'} if(render==='date'){const d=new Date(v);return isNaN(+d)?String(v):d.toLocaleString('fa-IR')} if(render==='status')return <span className="badge info">{String(v)}</span>; if(render==='image' || (typeof v==='string' && /^https?:\/\//.test(v) && /(jpg|jpeg|png|webp|avif)/i.test(v))) return <img className="thumb" src={v} alt=""/>; return typeof v==='object'?JSON.stringify(v):String(v)}
function initial(fields:FieldDef[]){const o:any={};fields.forEach(f=>{if(f.type==='boolean')o[f.key]=false;else o[f.key]=''});return o}
function Field({f,value,onChange}:{f:FieldDef;value:any;onChange:(v:any)=>void}){if(f.type==='boolean')return <label className="check"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/><span>{f.label}</span></label>; if(f.type==='image')return <label><span>{f.label}</span><div className="image-field">{value&&<img src={value} className="preview-image"/>}<input type="url" placeholder="آدرس تصویر یا URL آپلود" value={value??''} onChange={e=>onChange(e.target.value)}/></div></label>; if(f.type==='textarea'||f.type==='json')return <label><span>{f.label}{f.required&&' *'}</span><textarea rows={f.type==='json'?7:3} value={value??''} readOnly={f.readOnly} onChange={e=>onChange(e.target.value)}/></label>; return <label><span>{f.label}{f.required&&' *'}</span><input type={f.type==='decimal'||f.type==='number'?'number':f.type==='datetime'?'datetime-local':f.type||'text'} step={f.type==='decimal'?'any':undefined} value={value??''} readOnly={f.readOnly} onChange={e=>{let v:any=e.target.value;if((f.type==='number'||f.type==='decimal')&&v!=='')v=Number(v);onChange(v)}}/></label>}
export function ResourceManager({config}:{config:ResourceConfig}){
 const {show}=useToast(); const [rows,setRows]=useState<any[]>([]),[raw,setRaw]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1),[modal,setModal]=useState(false),[editing,setEditing]=useState<any>(null),[form,setForm]=useState<any>(()=>initial(config.fields)),[busy,setBusy]=useState(false),[selected,setSelected]=useState<any>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const q:any={...(config.list.defaultQuery||{})};if('page' in q)q.page=page;if(config.searchKey&&query)q[config.searchKey]=query;const x=await api(config.list.path,{query:q});setRaw(x);setRows(unwrapList(x));}catch(e:any){setError(e.message)}finally{setLoading(false)}},[config,page,query]);
 useEffect(()=>{const t=setTimeout(load,query?350:0);return()=>clearTimeout(t)},[load,query]);
 const idOf=(r:any)=>norm(r,config.idKey)??norm(r,'id');
 const openCreate=()=>{setEditing(null);setForm(initial(config.fields));setModal(true)};
 const openEdit=(r:any)=>{setEditing(r);const o:any={};config.fields.forEach(f=>{o[f.key]=norm(r,f.key)??(f.type==='boolean'?false:'')});setForm(o);setModal(true)};
 const save=async()=>{if(config.readOnly)return;for(const f of config.fields)if(f.required&&(form[f.key]===undefined||form[f.key]===null||form[f.key]==='')){show(`${f.label} الزامی است`,'error');return} setBusy(true);try{const endpoint=editing?config.update:config.create;if(!endpoint)throw new Error('عملیات برای این بخش تعریف نشده است.');const path=fillPath(endpoint.path,{id:idOf(editing||{})});const body={...form};Object.keys(body).forEach(k=>{if(body[k]==='')body[k]=null});await api(path,{method:endpoint.method,body});show(editing?'ویرایش با موفقیت انجام شد.':'رکورد جدید ایجاد شد.');setModal(false);await load()}catch(e:any){show(e.message,'error')}finally{setBusy(false)}};
 const remove=async(r:any)=>{if(!config.delete)return;if(!confirm(`حذف ${config.singular} با شناسه ${idOf(r)} انجام شود؟`))return;try{await api(fillPath(config.delete.path,{id:idOf(r)}),{method:'DELETE'});show('حذف انجام شد.');load()}catch(e:any){show(e.message,'error')}};
 const total=useMemo(()=>raw?.totalCount??raw?.data?.totalCount??raw?.total??rows.length,[raw,rows]);
 return <>
 <div className="page-head"><div><div className="eyebrow">{config.group}</div><h1>{config.title}</h1><p>{config.description}</p></div>{!config.readOnly&&config.create&&<button className="primary" onClick={openCreate}>＋ افزودن {config.singular}</button>}</div>
 <div className="toolbar"><div className="searchbox"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={config.searchKey?'جستجو...':'فیلتر در نتایج...'} /></div><button onClick={load} className="ghost">↻ بروزرسانی</button><div className="count">{Number(total||0).toLocaleString('fa-IR')} رکورد</div></div>
 <div className="card table-card">{error?<div className="error-state"><b>دریافت اطلاعات ناموفق بود</b><span>{error}</span><button onClick={load}>تلاش مجدد</button></div>:loading?<div className="loading"><i/><span>در حال دریافت اطلاعات از بک‌اند...</span></div>:rows.length===0?<div className="empty"><b>داده‌ای یافت نشد</b><span>پاسخ API خالی است یا فیلتر فعلی نتیجه‌ای ندارد.</span></div>:<div className="table-wrap"><table><thead><tr>{config.columns.map(c=><th key={c.key}>{c.label}</th>)}<th>عملیات</th></tr></thead><tbody>{rows.map((r,i)=><tr key={String(idOf(r)??i)} onClick={()=>setSelected(r)}>{config.columns.map(c=><td key={c.key}>{format(norm(r,c.key),c.render)}</td>)}<td className="actions" onClick={e=>e.stopPropagation()}>{!config.readOnly&&config.update&&<button onClick={()=>openEdit(r)}>ویرایش</button>}{config.delete&&<button className="danger-link" onClick={()=>remove(r)}>حذف</button>}<button onClick={()=>setSelected(r)}>جزئیات</button></td></tr>)}</tbody></table></div>}</div>
 {config.list.defaultQuery?.page!==undefined&&<div className="pagination"><button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>قبلی</button><span>صفحه {page.toLocaleString('fa-IR')}</span><button disabled={rows.length===0} onClick={()=>setPage(p=>p+1)}>بعدی</button></div>}
 {modal&&<div className="modal-layer" onMouseDown={()=>setModal(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><header><div><b>{editing?'ویرایش':'ایجاد'} {config.singular}</b><span>مقادیر مستقیماً به API Carnix ارسال می‌شوند.</span></div><button onClick={()=>setModal(false)}>×</button></header><div className="form-grid">{config.fields.filter(f=>!(f.readOnly&&!editing)).map(f=><Field key={f.key} f={f} value={form[f.key]} onChange={v=>setForm((x:any)=>({...x,[f.key]:v}))}/>)}</div><details className="json-preview"><summary>پیش‌نمایش JSON</summary><pre>{JSON.stringify(form,null,2)}</pre></details><footer><button className="ghost" onClick={()=>setModal(false)}>انصراف</button><button className="primary" disabled={busy} onClick={save}>{busy?'در حال ذخیره...':'ذخیره تغییرات'}</button></footer></div></div>}
 {selected&&<div className="drawer-layer" onMouseDown={()=>setSelected(null)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><header><div><b>جزئیات {config.singular}</b><span>شناسه: {String(idOf(selected)??'—')}</span></div><button onClick={()=>setSelected(null)}>×</button></header><div className="detail-grid">{Object.entries(selected).map(([k,v])=><div className="detail-item" key={k}><small>{k}</small><strong>{typeof v==='object'?JSON.stringify(v):String(v??'—')}</strong></div>)}</div></aside></div>}
 </>
}
