'use client';
import {useEffect,useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Heart,MapPin,Package,RotateCcw,ShoppingCart,Wrench} from 'lucide-react';
import {p4Api,type MechanicDashboard} from '@/features/p4/p4Api';
import {getMediaUrl} from '@/utils/media/getMediaUrl';
import {useHasMechanicRole} from '@/hooks/useMechanicRole';
import {useAppSelector} from '@/store/hooks';
import styles from './Dashboard.module.scss';
import { formatPrice } from '@/utils/price';
const money=(n:number)=>formatPrice(n);
export default function Dashboard(){const router=useRouter();const hasMechanicRole=useHasMechanicRole();const{initialized,isAuthenticated,roles}=useAppSelector((state)=>state.auth);const[data,setData]=useState<MechanicDashboard|null>(null);const[error,setError]=useState('');useEffect(()=>{if(!initialized)return;if(!isAuthenticated){router.replace('/login');return;}if(roles&&!hasMechanicRole){router.replace('/mechanics');}},[hasMechanicRole,initialized,isAuthenticated,roles,router]);useEffect(()=>{if(!hasMechanicRole)return;p4Api.mechanics.dashboard().then(setData).catch(()=>setError('دریافت اطلاعات پنل مکانیک انجام نشد.'))},[hasMechanicRole]);if(!initialized||!roles)return <main className={styles.state}>در حال بررسی دسترسی مکانیک…</main>;if(!isAuthenticated||!hasMechanicRole)return <main className={styles.state}>دسترسی به پنل مکانیک برای این حساب فعال نیست.</main>;if(error)return <main className={styles.state}>{error}</main>;if(!data)return <main className={styles.state}>در حال آماده‌سازی پنل مکانیک…</main>;const progress=Math.min(100,Math.round(data.points/Math.max(data.nextLevelPoints,1)*100));return <main className={styles.page} dir="rtl">
<header className={styles.profile}><div className={styles.avatar}>{data.avatarUrl?<Image src={getMediaUrl(data.avatarUrl)!} alt={data.profile.name} fill sizes="64px"/>:data.profile.name.trim().charAt(0)}</div><div><strong>{data.profile.name}</strong><span>{data.profile.shop} · مکانیک تاییدشده</span></div></header>
<section className={styles.level}><div className={styles.levelTop}><div><span>سطح فعلی</span><strong>مکانیک سطح {data.currentLevel.toLocaleString('fa-IR')}</strong></div><Wrench/></div><div className={styles.track}><i style={{width:`${progress}%`}}/></div><p>{data.points.toLocaleString('fa-IR')} امتیاز از {data.nextLevelPoints.toLocaleString('fa-IR')} امتیاز سطح بعد</p></section>
<h2>عملیات‌های سریع</h2><nav className={styles.quick}><Link href="/products"><ShoppingCart/><b>سفارش جدید</b><span>خرید قطعات خودرو</span></Link><Link href="/profile/orders"><RotateCcw/><b>تکرار خرید</b><span>سفارش‌های قبلی</span></Link><Link href="/profile/wishlist"><Heart/><b>علاقه‌مندی‌ها</b><span>محصولات ذخیره‌شده</span></Link><Link href="/mechanics"><Wrench/><b>نوبت‌ها</b><span>{data.pendingBookingCount.toLocaleString('fa-IR')} درخواست فعال</span></Link></nav>
<h2>عملکرد شما</h2><section className={styles.metrics}><article><span>تعداد سفارش</span><b>{data.orderCount.toLocaleString('fa-IR')}</b></article><article><span>مجموع خرید</span><b>{money(data.totalSpend)} تومان</b></article><article><span>صرفه‌جویی</span><b>{money(data.totalSavings)} تومان</b></article><article><span>درخواست فعال</span><b>{data.pendingBookingCount.toLocaleString('fa-IR')}</b></article></section>
<section className={styles.block}><div className={styles.heading}><h2>سفارش‌های اخیر</h2><Link href="/profile/orders">مشاهده همه</Link></div>{data.recentOrders.length?data.recentOrders.map(o=><article className={styles.order} key={o.orderId}><Package/><div><strong>سفارش {o.orderNumber}</strong><span>{new Date(o.createdAt).toLocaleDateString('fa-IR')} · {o.itemCount.toLocaleString('fa-IR')} محصول</span></div><b>{money(o.grandTotal)} تومان</b><em>{o.status}</em></article>):<p className={styles.empty}>هنوز سفارشی ثبت نشده است.</p>}</section>
<section className={styles.block}><div className={styles.heading}><h2>درخواست‌های تعمیر</h2><Link href="/mechanics">رزرو جدید</Link></div>{data.recentBookings.length?data.recentBookings.map(b=><article className={styles.booking} key={b.mechanicBookingId}><Wrench/><div><strong>{b.service}</strong><span>{b.vehicle} · {new Date(b.appointmentDate).toLocaleDateString('fa-IR')}</span></div><em>{b.status==='pending'?'در انتظار بررسی':b.status==='confirmed'?'تایید شده':'لغو شده'}</em></article>):<p className={styles.empty}>هنوز درخواست تعمیری ثبت نشده است.</p>}</section>
<section className={styles.twoCols}><div className={styles.block}><div className={styles.heading}><h2>دسته‌بندی‌های مورد علاقه</h2></div><div className={styles.categories}>{data.favoriteCategories.map(x=><span key={x}>{x}</span>)}{!data.favoriteCategories.length&&<p className={styles.empty}>هنوز دسته‌ای انتخاب نشده است.</p>}</div></div><div className={styles.block}><div className={styles.heading}><h2>آدرس‌ها</h2><Link href="/profile/addresses">مدیریت</Link></div>{data.addresses.map(x=><article className={styles.address} key={x.userAddressId}><MapPin/><div><strong>{x.title}</strong><span>{x.city}، {x.fullAddress}</span></div></article>)}{!data.addresses.length&&<p className={styles.empty}>هنوز آدرسی ثبت نشده است.</p>}</div></section></main>}
