import axiosClient from '@/services/api/common/axiosClient';
import { unwrapApiData } from '@/services/api/common/apiError';
export type GarageVehicle={garageVehicleId:number;title:string;year:string;plate:string;mileage:number;imageUrl?:string|null;createdAt:string};
export type UserNotice={customerNotificationId:number;title:string;body:string;createdAt:string;isRead:boolean;href?:string};
export type TicketReply={customerTicketReplyId:number;body:string;isFromSupport:boolean;createdAt:string};
export type SupportTicket={customerTicketId:number;subject:string;category:string;message:string;status:'open'|'answered'|'closed';createdAt:string;replies:TicketReply[]};
export type Mechanic={mechanicProfileId:number;slug:string;name:string;shop:string;city:string;district:string;rating:number;reviews:number;experience:number;isVerified:boolean;servicesJson:string;vehiclesJson:string;about:string;phone:string};
export type MechanicBooking={mechanicBookingId:number;mechanicProfileId:number;service:string;appointmentDate:string;vehicle:string;status:'pending'|'confirmed'|'cancelled';createdAt:string;mechanic?:Mechanic};
export type MechanicDashboardBooking={mechanicBookingId:number;mechanicProfileId:number;service:string;appointmentDate:string;vehicle:string;status:string;createdAt:string};
export type MechanicDashboardOrder={orderId:number;orderNumber:string;status:string;grandTotal:number;discountTotal:number;itemCount:number;createdAt:string};
export type MechanicDashboardAddress={userAddressId:number;title:string;fullAddress:string;city:string;isDefault:boolean};
export type MechanicDashboard={profile:Mechanic;avatarUrl?:string|null;currentLevel:number;points:number;nextLevelPoints:number;orderCount:number;totalSpend:number;totalSavings:number;pendingBookingCount:number;recentOrders:MechanicDashboardOrder[];recentBookings:MechanicDashboardBooking[];favoriteCategories:string[];addresses:MechanicDashboardAddress[]};
export type DiagnosticRule={diagnosticRuleId:number;systemKey:string;systemTitle:string;symptomKey:string;symptomTitle:string;causesJson:string;searchTerm:string;service:string;isUrgent:boolean};
export type CompatibilityProduct={productId:number;name:string;basePrice:number;totalStock:number;imageUrl?:string|null};
export type DiagnosticEvaluation={rule:DiagnosticRule;garage?:GarageVehicle|null;mechanics:Mechanic[];products:CompatibilityProduct[];severity:string;when:string};
export const parseList=(value:string):string[]=>{try{const x=JSON.parse(value);return Array.isArray(x)?x:[]}catch{return[]}};
export const p4Api={
 garage:{list:async()=>unwrapApiData<GarageVehicle[]>((await axiosClient.get('/p4/garage')).data),add:async(input:{title:string;year:string;plate:string;mileage:number})=>unwrapApiData<GarageVehicle>((await axiosClient.post('/p4/garage',input)).data),update:async(id:number,input:{title:string;year:string;plate:string;mileage:number})=>unwrapApiData<GarageVehicle>((await axiosClient.put(`/p4/garage/${id}`,input)).data),remove:async(id:number)=>void await axiosClient.delete(`/p4/garage/${id}`),compatibility:async(id:number)=>unwrapApiData<{garage:GarageVehicle;products:CompatibilityProduct[]} >((await axiosClient.get(`/p4/garage/${id}/compatibility`)).data)},
 notices:{list:async()=>unwrapApiData<UserNotice[]>((await axiosClient.get('/p4/notifications')).data),markAllRead:async()=>void await axiosClient.post('/p4/notifications/read-all')},
 tickets:{list:async()=>unwrapApiData<SupportTicket[]>((await axiosClient.get('/p4/tickets')).data),add:async(input:{subject:string;category:string;message:string})=>unwrapApiData<SupportTicket>((await axiosClient.post('/p4/tickets',input)).data),get:async(id:number)=>unwrapApiData<SupportTicket>((await axiosClient.get(`/p4/tickets/${id}`)).data),reply:async(id:number,body:string)=>void await axiosClient.post(`/p4/tickets/${id}/replies`,{body}),close:async(id:number)=>void await axiosClient.post(`/p4/tickets/${id}/close`)},
 mechanics:{list:async(q='',city='all')=>unwrapApiData<Mechanic[]>((await axiosClient.get('/p4/mechanics',{params:{q,city}})).data),get:async(slug:string)=>unwrapApiData<Mechanic>((await axiosClient.get(`/p4/mechanics/${slug}`)).data),me:async()=>unwrapApiData<Mechanic>((await axiosClient.get('/p4/mechanic/me')).data),dashboard:async()=>unwrapApiData<MechanicDashboard>((await axiosClient.get('/p4/mechanic/dashboard')).data)},
 bookings:{list:async()=>unwrapApiData<MechanicBooking[]>((await axiosClient.get('/p4/bookings')).data),add:async(input:{mechanicProfileId:number;service:string;appointmentDate:string;vehicle:string})=>unwrapApiData<MechanicBooking>((await axiosClient.post('/p4/bookings',input)).data),cancel:async(id:number)=>void await axiosClient.post(`/p4/bookings/${id}/cancel`)},
 diagnostics:{list:async()=>unwrapApiData<DiagnosticRule[]>((await axiosClient.get('/p4/diagnostics')).data),evaluate:async(input:{diagnosticRuleId:number;severity:string;when:string;garageVehicleId?:number})=>unwrapApiData<DiagnosticEvaluation>((await axiosClient.post('/p4/diagnostics/evaluate',input)).data)},
};
